### ISSUE TITLE
rmarkdown example fails

### ISSUE THREAD

**Issue by bkamapantula** [gramener/gramex-guide#44] opened 2020-12-02 04:18 UTC
doc link: https://learn.gramener.com/guide/r/#rmarkdown

demo link: https://learn.gramener.com/guide/r/RMarkdown-story.Rmd

error:

ValueError('Buffer for this type not yet supported.')

also noticed by @shiva-1605

**Comment by sanand0** [comment] 2020-12-18 04:38
Duplicate of https://github.com/gramener/gramex/issues/259

**Closed by sanand0** 2020-12-18 04:38 UTC
