### ISSUE TITLE
File Missing

### ISSUE THREAD

**Issue by arkadeep-baksi** [gramener/gramex-guide#75] opened 2021-03-23 15:19 UTC
In the Gramex Documentation, in the Gramex Apps ,Language Tools section ,the following links in the Examples subsection are giving error messages :- 1) https://learn.gramener.com/guide/languagetool/languagetool/?q=The%20quick%20brown%20fox%20jamp%20over%20the%20lazy%20dog. 2) https://learn.gramener.com/guide/languagetool/languagetool/?q=how%20are%20you 3) https://learn.gramener.com/guide/languagetool/languagetool/?q=I%20is%20fine.

**Comment by jaidevd** [comment] 2021-03-25 13:50
Duplicate of #63 , closing.

**Closed by jaidevd** 2021-03-25 13:50 UTC
